springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true

azure:
  application-insights:
    instrumentation-key: ${PETSTORESERVICES_AI_INSTRUMENTATION_KEY:e9fc272f-5d38-406b-b496-02cae7d3fd0f}
